'use client';import { useState } from 'react';
export default function Page(){
const[tab,setTab]=useState('login');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[rpass,setRpass]=useState('');const[rcpass,setRcpass]=useState('');
const login=async(e)=>{e.preventDefault();localStorage.setItem('milan_user',JSON.stringify({email,did:'did:dht:demo'}));location.href='/';};
const register=async(e)=>{e.preventDefault();if(rpass!==rcpass){alert('Passwords mismatch');return;}localStorage.setItem('milan_user',JSON.stringify({email,name,did:'did:dht:'+Date.now()}));location.href='/';};
return(<><style>{`*{margin:0;padding:0;box-sizing:border-box}html,body{height:100vh;overflow:hidden;background:#060608;color:white;font-family:Inter,sans-serif} .top{height:52px;display:flex;justify-content:space-between;align-items:center;padding:0 28px;border-bottom:1px solid rgba(255,255,255,0.06)} .desk{height:calc(100vh - 52px);display:grid;grid-template-columns:1.1fr 0.9fr;max-width:1440px;margin:0 auto} .card{width:100%;max-width:400px;background:linear-gradient(180deg,rgba(255,255,255,0.07),rgba(255,255,255,0.02));border:1px solid rgba(255,255,255,0.1);border-radius:24px;padding:22px} .tabs{display:flex;gap:4px;padding:4px;background:rgba(0,0,0,0.5);border-radius:10px;margin-bottom:16px} .tab{flex:1;padding:8px;border-radius:8px;font-size:12px;font-weight:700;text-align:center;cursor:pointer;color:#71717a} .active{background:white;color:black} .input{width:100%;padding:11px 12px;border-radius:10px;background:rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.1);color:white;margin-bottom:8px} .btn{width:100%;padding:11px;border-radius:10px;background:white;color:black;font-weight:800;border:none}`}</style>
<div style={{height:'100vh',overflow:'hidden',background:'#060608'}}>
<div className="top"><div style={{fontWeight:800}}>MILAN</div><div style={{fontSize:'10px',color:'#9f9fa9'}}>TOP CARD • Login + Register • No Scroll</div></div>
<div className="desk">
<div style={{padding:'20px 36px',display:'flex',flexDirection:'column',justifyContent:'center',gap:'12px'}}><div style={{fontSize:'56px',fontWeight:800,lineHeight:0.88}}>Your Space.<br/>Your People.<br/><span style={{background:'linear-gradient(90deg,#a78bfa,#f472b6)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>Owned by you.</span></div></div>
<div style={{display:'grid',placeItems:'center',padding:'12px 24px'}}>
<div className="card">
<div className="tabs"><div className={`tab ${tab==='login'?'active':''}`} onClick={()=>setTab('login')}>Sign in</div><div className={`tab ${tab==='register'?'active':''}`} onClick={()=>setTab('register')}>Register</div></div>
{tab==='login'?<form onSubmit={login}><input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email or DID" required/><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button className="btn" type="submit">Sign in →</button><div style={{marginTop:'8px',fontSize:'11px',color:'#71717a',textAlign:'center'}}>No DID? <span style={{color:'white',cursor:'pointer'}} onClick={()=>setTab('register')}>Register</span></div></form>:<form onSubmit={register}><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Full Name" required/><input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" required/><input className="input" type="password" value={rpass} onChange={e=>setRpass(e.target.value)} placeholder="Password" required/><input className="input" type="password" value={rcpass} onChange={e=>setRcpass(e.target.value)} placeholder="Confirm Password" required/><button className="btn" type="submit">Create DID →</button><div style={{marginTop:'8px',fontSize:'11px',color:'#71717a',textAlign:'center'}}>Have DID? <span style={{color:'white',cursor:'pointer'}} onClick={()=>setTab('login')}>Sign in</span></div></form>}
</div>
</div>
</div>
</div></>);
}
